module cla_adder_8bit_reg (
    input wire clk,
    input wire rst_n, // Asynchronous active-low reset
    input wire [7:0] A,
    input wire [7:0] B,
    input wire Cin,
    output reg [7:0] Sum,
    output reg Cout
);

    // Internal signals for Propagate (P) and Generate (G) terms for each bit
    wire [7:0] P;
    wire [7:0] G;

    // Internal signals for carries.
    // C_int[0] is the initial carry-in (Cin).
    // C_int[i] is the carry into bit 'i'.
    // C_int[8] is the final carry-out (Cout).
    wire [8:0] C_int;

    // Combinational sum and carry-out before registration
    wire [7:0] S_comb;
    wire C_out_comb;

    // 1. Calculate Propagate (P) and Generate (G) terms for each bit
    // Pi = Ai XOR Bi (Propagate: carry propagates through this bit if Cin=1)
    // Gi = Ai AND Bi (Generate: carry is generated by this bit, regardless of Cin)
    assign P = A ^ B;
    assign G = A & B;

    // 2. Initialize the first carry (carry-in to bit 0)
    assign C_int[0] = Cin;

    // 3. Calculate carries using Carry Lookahead logic
    // Ci+1 = Gi | (Pi & Gi-1) | (Pi & Pi-1 & Gi-2) | ... | (Pi & ... & P0 & C0)
    // C_int[i+1] represents the carry generated for the i-th bit position (to be fed into bit i+1)
    assign C_int[1] = G[0] | (P[0] & C_int[0]);
    assign C_int[2] = G[1] | (P[1] & G[0]) | (P[1] & P[0] & C_int[0]);
    assign C_int[3] = G[2] | (P[2] & G[1]) | (P[2] & P[1] & G[0]) | (P[2] & P[1] & P[0] & C_int[0]);
    assign C_int[4] = G[3] | (P[3] & G[2]) | (P[3] & P[2] & G[1]) | (P[3] & P[2] & P[1] & G[0]) | (P[3] & P[2] & P[1] & P[0] & C_int[0]);
    assign C_int[5] = G[4] | (P[4] & G[3]) | (P[4] & P[3] & G[2]) | (P[4] & P[3] & P[2] & G[1]) | (P[4] & P[3] & P[2] & P[1] & G[0]) | (P[4] & P[3] & P[2] & P[1] & P[0] & C_int[0]);
    assign C_int[6] = G[5] | (P[5] & G[4]) | (P[5] & P[4] & G[3]) | (P[5] & P[4] & P[3] & G[2]) | (P[5] & P[4] & P[3] & P[2] & G[1]) | (P[5] & P[4] & P[3] & P[2] & P[1] & G[0]) | (P[5] & P[4] & P[3] & P[2] & P[1] & P[0] & C_int[0]);
    assign C_int[7] = G[6] | (P[6] & G[5]) | (P[6] & P[5] & G[4]) | (P[6] & P[5] & P[4] & G[3]) | (P[6] & P[5] & P[4] & P[3] & G[2]) | (P[6] & P[5] & P[4] & P[3] & P[2] & G[1]) | (P[6] & P[5] & P[4] & P[3] & P[2] & P[1] & G[0]) | (P[6] & P[5] & P[4] & P[3] & P[2] & P[1] & P[0] & C_int[0]);
    assign C_int[8] = G[7] | (P[7] & G[6]) | (P[7] & P[6]